name = "land-vista-form"
main = "src/index.ts"
compatibility_date = "2025-07-15"

[vars]
SANITY_PROJECT_ID = "yourprojectid"
SANITY_DATASET = "production"
SANITY_WRITE_TOKEN = "skw_xxxxxxxxxxxxxxxxx"

# Optional: Custom domain routing
# [routes]
# pattern = "https://land-vista.github.io/*"
# zone_id = ""